### ISSUE TITLE
Upgrade LaxarJS to v1.0.0

### ISSUE THREAD

**Issue by jonaswjs** [LaxarJS/mashup_demo#10]
Upgrade LaxarJS version to 1.x and fit application and internal widgets to the new version.

**Comment by alex3683** [comment]
@jonaswjs: While you're at it, please rename the repository and according widget categories and paths to `widget-browser` (i.e. replace underscore with dash).

**Comment by jonaswjs** [comment]
Implemented on `master` (`v1.0.0`)
